repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-json

- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.17
  hooks:
  - id: mdformat
    additional_dependencies: [mdformat-gfm]

# （任意）将来データJSONのスキーマ検証を有効化する時に追記
# - repo: https://github.com/python-jsonschema/check-jsonschema
#   rev: 0.29.1
#   hooks:
#   - id: check-jsonschema
#     files: ^data/overlays/.*\.json$
#     args: [--schemafile, docs/templates/overlays/valuation_overlay.schema.json]
