domain_whitelist:
  - sec.gov
  - investors.confluent.io
require_text_fragment: true
verbatim_max_words: 25
require_anchor_backup: true
find_path_enum: [xbrl, note, md&a, fallback_text, manual]
placeholders_forbidden: ["\\[[0-9]+\\]", "(?i)not_found", "(?i)PLACEHOLDER"]
dual_anchor_policy:
  primary: SEC
  secondary: IR
  fallback_when_sec_blocked: true
