# AHF Lexicon Configuration
# 因果判定・正規化・抽出のための辞書設定

# T判定用因果動詞（機械ルール）
causal_verbs:
  - "due to"
  - "driven by" 
  - "primarily due to"
  - "resulting from"
  - "offset by"
  - "because of"
  - "attributable to"
  - "stemming from"

# 売上総利益関連の同義語
gm_aliases:
  - "gross margin"
  - "cost of revenues"
  - "COGS"
  - "cost of goods sold"
  - "cost of sales"
  - "cost of revenue"
  - "gross profit"

# 方向性判定用語彙
direction_up:
  - "increased"
  - "higher"
  - "rose"
  - "expanded"
  - "improved"
  - "enhanced"
  - "gained"
  - "strengthened"

direction_down:
  - "decreased"
  - "lower"
  - "declined"
  - "contracted"
  - "deteriorated"
  - "weakened"
  - "reduced"
  - "fell"

# 期間表現の正規化
period_patterns:
  quarter_over_quarter:
    - "quarter over quarter"
    - "qoq"
    - "compared to the prior quarter"
    - "from the prior quarter"
    - "vs prior quarter"
  
  year_over_year:
    - "year over year"
    - "yoy"
    - "compared to the prior year"
    - "from the prior year period"
    - "vs prior year"

# 数値単位の正規化
unit_patterns:
  millions:
    - "million"
    - "m"
    - "$m"
    - "mill"
  
  percentage_points:
    - "percentage point"
    - "pp"
    - "basis point"
    - "bp"
  
  percentage:
    - "percent"
    - "%"
    - "pct"

# 誤検知除外リスト（差分学習用）
denylist:
  - "due to market conditions"  # 曖昧な表現
  - "driven by external factors"  # 具体性不足
  - "primarily due to seasonality"  # 一時的要因

# アンカリング検証用パターン
anchor_patterns:
  quote_indicators:
    - '"'
    - "'"
    - "stated"
    - "noted"
    - "mentioned"
    - "reported"
  
  source_indicators:
    - "management"
    - "we"
    - "the company"
    - "our"
    - "according to"
