stage1:
  # v0.7.1c ハイコントラスト版RSS設定
  rs_dr_high: 8.0                    # DR_qoq ≥ +8% で高成長
  rs_bookings_high: 10.0             # Bookings_qoq ≥ +10% で高成長
  dr_guard_threshold: 2               # DR 2Q連続減で★≤2に即降格

stage2:
  alpha3:
    drift_pp_threshold: 0.2           # |drift| > 0.2pp で機械NG
    residual_gp_max_usd: 8000000      # $8.0M 以内でもpp超過はNG
    # v0.7.1c ハイコントラスト版
    alpha3_near_pp: 0.8               # ≤0.8pp で「説明付き近接」評価
  alpha5:
    median_minus_actual_max_usd: -3000000  # ≤ -$3M で「改善の素地あり」
    # v0.7.1c ハイコントラスト版
    alpha5_weak_band: [-3000000, -1000000]  # -$3M < 差 ≤ -$1M で「弱い改善」
    efficiency_phrases: [
      "operating leverage",
      "operating discipline", 
      "hiring pacing",
      "cost discipline",
      "cost control",
      "efficiency improvements",
      "operational efficiency"
    ]
  watch:
    require_only_if_needed: true      # 片翼NGの時だけ CL/CA・Item1A を確認
  interrupts:
    - code: A3_UNEXPLAINED
      when: "alpha3_fail AND NOT mdna_explained"
    - code: BALANCE_WEAK
      when: "CL_down AND CA_up"
    - code: ITEM1A_CHANGE
      when: "item1a_changed"
    - code: ANCHOR_FAIL
      when: "anchor_lint_fail"