# AHF Ticker Configuration
# 追加ティッカーはこのファイルでYAML1枚で増設

tickers:
  DUOL:
    cik: "0001551158"
    ir_domain: "investor.duolingo.com"
    sector: "Technology"
    currency: "USD"
    segment_name: "Language Learning"
    reporting_units:
      revenue: "millions"
      gross_margin: "percentage_points"
      operating_expense: "millions"
      rpo: "millions"
    
  RKLB:
    cik: "0001818874"
    ir_domain: "investor.rocketlabusa.com"
    sector: "Aerospace"
    currency: "USD"
    segment_name: "Launch Services & Space Systems"
    reporting_units:
      revenue: "millions"
      gross_margin: "percentage_points"
      operating_expense: "millions"
      backlog: "millions"

# 新規ティッカー追加時のテンプレート
# TICKER_SYMBOL:
#   cik: "0000000000"
#   ir_domain: "investor.company.com"
#   sector: "Sector Name"
#   currency: "USD"
#   segment_name: "Business Segment"
#   reporting_units:
#     revenue: "millions"
#     gross_margin: "percentage_points"
#     operating_expense: "millions"
